apiVersion: v1
kind: Service
metadata:
  name: shopfront
  namespace: java
  labels:
    app: shopfront
spec:
  type: NodePort
  selector:
    app: shopfront
  ports:
  - name: http
    port: 8010
    protocol: TCP
